#服务
server:
  port: 8080

spring:
  #数据库
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/weixin?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

#mybatis配置文件地址
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.weixin.entity
